[package]
name = "heartwood-trial"
version = "0.1.0"
description = "Heartwood Trial"
authors = ["Wood-Booster"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "heartwood_trial_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.3", features = [] }
