[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wood-booster-os"
version = "2.0.0"
description = "Wood-Booster OS featuring Win96 components and the epic Kalevala Subsystem"
readme = "README.md"
authors = [
    { name = "Marc Järvinen" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "colorama>=0.4.6",
    "pyyaml>=6.0.1"
]

[tool.setuptools.packages.find]
where = ["src"]
