import { chromium } from "playwright"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
page.on("console", (m) => console.log("[console]", m.text()))
await page.goto("http://localhost:5189/hearthwood-studio", { waitUntil: "domcontentloaded" })
await page.waitForTimeout(1000)
await page.click("text=Single")
await page.waitForTimeout(500)
await page.click("text=+ Add new")
await page.waitForTimeout(500)
await page.click("text=Preview clone")
await page.waitForTimeout(1500)
const bodyText = await page.evaluate(() => document.querySelector(".space-y-2.rounded-xl")?.textContent || "NOT FOUND")
console.log("Clone form text after preview click:", bodyText)
await page.screenshot({ path: "/tmp/debug_addnew_preview.png" })
await browser.close()
