import { chromium } from "playwright"
const PORT = process.env.PORT || 5227
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1000, height: 1400 } })
await page.goto(`http://localhost:${PORT}/heartwood`)
await page.waitForTimeout(500)
await page.click(".hw-select-grid button")
const tutorialNext = page.locator(".hw-tutorial-next")
if (await tutorialNext.isVisible({ timeout: 2000 }).catch(() => false)) await tutorialNext.click().catch(() => {})
await page.waitForTimeout(300)
await page.locator(".hw-item-card").first().click()
await page.waitForTimeout(150)
await page.locator(".hw-badge", { hasText: "Ember Charm" }).first().click()
await page.waitForTimeout(150)
await page.locator(".hw-item-slot").first().click()
await page.waitForTimeout(300)
await page.screenshot({ path: "/tmp/heartwood_items_shop.png", fullPage: true })
await browser.close()
console.log("saved")
