// Look & feel screenshots of the tactics prototype board (not a verify suite).
import { chromium } from "playwright"
const OUT = process.argv[2] || "/tmp/shot"
const browser = await chromium.launch()
const page = await (await browser.newContext({ viewport: { width: 1300, height: 900 }, deviceScaleFactor: 2 })).newPage()
const errs = []
page.on("pageerror", (e) => errs.push(e.message))
await page.goto("http://localhost:5441/heartwood-tactics")
await page.waitForSelector(".hwt-board")
await page.waitForTimeout(800)
await page.screenshot({ path: `${OUT}-1-board.png` })
const tok = page.locator('.hwt-token[data-selectable="true"]').first()
await tok.click()
await page.waitForTimeout(400)
await page.screenshot({ path: `${OUT}-2-selected.png` })
const reach = page.locator('.hwt-cell[data-reachable="true"]')
if (await reach.count()) await reach.last().click()
await page.waitForTimeout(400)
await page.locator(".hwt-end-turn").click()
await page.waitForTimeout(2500)
await page.screenshot({ path: `${OUT}-3-after-turn.png` })
const b = await page.locator(".hwt-board").boundingBox()
await page.screenshot({ path: `${OUT}-4-zoom.png`, clip: { x: b.x + b.width - 420, y: b.y + 150, width: 420, height: 330 } })
const p = await page.locator(".hwt-panel").boundingBox()
await page.locator(".hwt-formation-btn", { hasText: "The Crossing" }).click()
await page.waitForTimeout(700)
await page.screenshot({ path: `${OUT}-5-terrain.png`, clip: { x: b.x, y: b.y, width: 640, height: 560 } })
console.log("board", JSON.stringify(b), "panel", JSON.stringify(p))
console.log("errors", errs)
await browser.close()
