import { chromium } from "playwright"
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } })
await page.goto("http://localhost:5188/hearthwood-studio", { waitUntil: "domcontentloaded" })
await page.waitForTimeout(1000)
await page.click("text=Single")
await page.waitForTimeout(300)
await page.click("text=📖 Story Timeline")
await page.waitForTimeout(500)
await page.screenshot({ path: "/tmp/timeline_add_default.png" })
await page.click("text=+ New Dialogue")
await page.waitForTimeout(400)
await page.screenshot({ path: "/tmp/timeline_add_dialogue_form.png" })
await browser.close()
